apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../_common

namespace: demo


replicas:
- count: 1
  name: demo-app

configMapGenerator:
- files:
  - config.json
  name: demo-app-config

generatorOptions:
  disableNameSuffixHash: true

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: demo-app
  target:
    name: NAME_PLACEHOLDER
- path: deployment-patch.yaml


images:
- name: wadexu007/demo-app
  newTag: 1.0.0
labels:
- includeSelectors: true
  pairs:
    app: demo-app
