---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  labels:
    app.kubernetes.io/component: ambassador-service
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 35.222.10.10
  selector:
    service: ambassador
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
