def dir_path = "Jenkins/kaniko-demo"
def yaml_path = dir_path + '/build-pod.yaml'

pipeline {
  options {
    timeout(time: 10, unit: 'MINUTES')
    buildDiscarder(logRotator(numToKeepStr: '10', daysToKeepStr: '7'))
  }

  agent {
    kubernetes {
      idleMinutes 3  // how long the pod will live after no jobs have run on it
      yamlFile yaml_path  // path to the pod definition relative to the root of our project 
      defaultContainer 'docker'  // define a default container if more than a few stages use it, otherwise default to jnlp container
    }
  }
  stages {

    stage('Init') {
      steps {
        script {
          container('git') {
            sh """git config --global --add safe.directory $WORKSPACE"""
            def image_tag = env.BRANCH_NAME + "-" + env.BUILD_NUMBER
            def image_name = env.JOB_NAME.split("/")[0]
            env.PROJECT_IMAGE_WITH_TAG = image_name + ":" + image_tag
            sh 'env'
          }
        }
      }
    }

    stage('Kaniko Build and Push Docker Image') {
      steps {
        script {
          dir(dir_path) {
            container('kaniko') {
              sh """
                /kaniko/executor --context `pwd` --destination wadexu007/$PROJECT_IMAGE_WITH_TAG
              """
            }
          }
        }
      }
    }

  }
}