---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atlantis
  namespace: atlantis
data:
  config.yaml: |-
    checkout-strategy: merge
    data-dir: /atlantis
    default-tf-version: v1.1.5
    enable-diff-markdown-format: true
    hide-prev-plan-comments: true
    log-level: info

  repoConfig.yaml: |-
    repos:
    - id: /.*/
      branch: /(master|main)/
      apply_requirements: [approved, mergeable]
      allowed_overrides: [apply_requirements, workflow, delete_source_branch_on_merge]
      workflow: default
    - id: github.com/wadexu007/learning_by_doing
      apply_requirements: [approved, mergeable]
      allowed_overrides: [apply_requirements, workflow, delete_source_branch_on_merge]
      workflow: my-demo
    workflows:
      default:
        plan:
          steps:
            - init
            - plan
        apply:
          steps:
            - apply
      my-demo:
        plan:
          steps:
            - env:
                name: ENV_NAME
                command: 'echo "dynamic-value-$(date)"'
            - run: terraform${ATLANTIS_TERRAFORM_VERSION} fmt -check=true -write=false -diff=true
            - init
            - plan
        apply:
          steps:
            - apply
