// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package router

import (
	"main.go/controller/account"
	"main.go/repository"
	"main.go/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func initUserController(db2 *gorm.DB) account.UserController {
	userRepository := repository.NewUserRepository(db2)
	userService := service.NewUserService(userRepository)
	userController := account.NewUserController(userService)
	return userController
}
