apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../_common
- hosts.yaml
- mappings.yaml
- listeners.yaml

patches:
  - path: service-patch.yaml
    target:
      kind: Service
      name: emissary-ingress

# default is 3, change to 1 for demo purpose
replicas:
- name: emissary-ingress
  count: 1

# if you change namespace, kustomize will also change CRDs in emissary-system namespace.
namespace: emissary-system
