apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- modules.yaml
- resolvers.yaml
patchesStrategicMerge:
- deployment-patch.yaml
patches:
- target:
    kind: ClusterRoleBinding
    name: ambassador
  patch: |-
    - op: replace
      path: /metadata/name
      value: ambassador-dmz
images:
- name: docker.io/datawire/ambassador:\$version\$
  newName: asia.gcr.io/devops-apac-mgmt/ambassador
  newTag: 1.12.1
