apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- modules.yaml
- resolvers.yaml

# when you have both public and internal ambassador in one cluster
# need separate name of ClusterRoleBinding
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: ambassador-dmz
  target:
    kind: ClusterRoleBinding
    name: ambassador
- path: deployment-patch.yaml

# replace container registry and ambassador version
images:
- name: docker.io/datawire/ambassador:\$version\$
  newName: docker.io/datawire/ambassador
  newTag: 1.12.1
