apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://app.getambassador.io/yaml/emissary/3.2.0/emissary-crds.yaml
- https://app.getambassador.io/yaml/emissary/3.2.0/emissary-emissaryns.yaml
