apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- serviceaccount.yaml
- clusterrolebinding.yaml
- crds.yaml
- deployment.yaml
- backupstoragelocation.yaml
- volumesnapshotlocation.yaml
- schedules.yaml
