---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: SA@PROJECT.iam.gserviceaccount.com
  labels:
    component: velero
  name: velero
  namespace: velero

