---
apiVersion: v1
kind: Namespace
metadata:
  name: test

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: tls-secret
  namespace: test
spec:
  backendType: gcpSecretsManager
  template:
    type: kubernetes.io/tls
  data:
    - key: tls-secret
      name: tls.crt
      version: latest
      property: tls.crt
      isBinary: true
    - key: tls-secret
      name: tls.key
      version: latest
      property: tls.key
      isBinary: true
