apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-us-dev
  namespace: argocd
  labels:
    application-type: deployment
spec:
  destination:
    namespace: demo
    server: https://34.28.199.211
  project: gke-us-dev-project
  source:
    path: Kustomize/demo-manifests/services/demo-app/dev
    repoURL: https://github.com/wadexu007/learning_by_doing
    targetRevision: main
    kustomize:
      commonLabels:
        managed-by: argo-kustomize
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false