apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- resolvers.yaml
- namespace.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: emissary-ingress
  - path: modules.yaml
    target:
      kind: Module
      name: ambassador
