apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-us-mgmt
  namespace: argocd
  labels:
    application-type: deployment
spec:
  destination:
    namespace: mgmt-demo
    server: https://kubernetes.default.svc
  project: gke-us-mgmt-project
  source:
    path: Kustomize/demo-manifests/services/demo-app/dev
    repoURL: https://github.com/wadexu007/learning_by_doing
    targetRevision: main
    kustomize:
      commonLabels:
        managed-by: argo-kustomize
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=false