apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-agent
  labels:
    app: opentelemetry
    component: otel-collector
  namespace: otel
data:
  otel-collector-agent: |
    receivers:
      hostmetrics:
        collection_interval: 10s
        scrapers:
          cpu: 
          disk: 
          filesystem: 
          load: 
          memory: 
          network: 
      kubeletstats:
        auth_type: serviceAccount
        collection_interval: 20s
        endpoint: ${K8S_NODE_NAME}:10250
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_mib: 409
        spike_limit_mib: 128
      metricstransform:
        transforms:
          include: .+
          match_type: regexp
          action: update
          operations:
            - action: add_label
              new_label: cluster_name
              new_value: sre-test-cluster
            - action: add_label
              new_label: env_type
              new_value: host
    extensions:
      health_check: {}
    exporters:
      logging:
        verbosity: normal
      prometheusremotewrite:
        endpoint: https://<userID>:<Grafana API Key>@prometheus-us-central1.grafana.net/api/prom/push
        resource_to_telemetry_conversion:
          enabled: true
    service:
      extensions: 
      - health_check
      pipelines:
        metrics:
          receivers: [hostmetrics, kubeletstats]
          processors: [batch, memory_limiter, metricstransform]
          exporters: [prometheusremotewrite]

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector-agent
  labels:
    app: opentelemetry
    component: otel-collector
  namespace: otel
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
        
    spec:  
      serviceAccountName: otel-collector
      containers:
        - name: otel-collector
          command:
            - "/otelcol-contrib"
            - "--config=/conf/otel-collector-agent.yaml"
          image: otel/opentelemetry-collector-contrib:0.64.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: otlp
              containerPort: 4317
              protocol: TCP
              hostPort: 4317
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
              hostPort: 4318
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: HOST_PROC
              value: /hostfs/proc
            - name: HOST_SYS
              value: /hostfs/sys
            - name: HOST_ETC
              value: /hostfs/etc
            - name: HOST_VAR
              value: /hostfs/var
            - name: HOST_RUN
              value: /hostfs/run
            - name: HOST_DEV
              value: /hostfs/dev
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 13133
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 13133

          resources:
            limits:
              cpu: 256m
              memory: 512Mi
          volumeMounts:
            - mountPath: /conf
              name: otel-collector-conf-vol
            - name: hostfs
              mountPath: /hostfs
              readOnly: true
              mountPropagation: HostToContainer
      volumes:
        - name: otel-collector-conf-vol
          configMap:
            name: otel-collector-agent
            items:
              - key: otel-collector-agent
                path: otel-collector-agent.yaml
        - name: hostfs
          hostPath:
            path: /
      hostNetwork: false
