apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../_common
  - ingress.yaml
  - service.yaml

namespace: app

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
