apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-manager
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: argocd-manager
  name: argocd-manager-token
type: kubernetes.io/service-account-token