apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../_common
- hosts.yaml
- mappings.yaml
- listeners.yaml

patches:
  - path: service-patch.yaml
    target:
      kind: Service
      name: emissary-ingress

  # ClusterRoleBinding need patch to replace name to avoid overrided 
  # only need when multiple Ambassadors(Emissary) in one cluster
  - target:
      kind: ClusterRoleBinding
      name: emissary-ingress
    patch: |-
      - op: replace
        path: /metadata/name
        value: emissary-ingress-private
  - target:
      kind: ClusterRoleBinding
      name: emissary-ingress-agent
    patch: |-
      - op: replace
        path: /metadata/name
        value: emissary-ingress-private-agent

# default is 3, change to 1 for demo purpose
replicas:
- name: emissary-ingress
  count: 1

namespace: dmz-private
