apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod-istio
  namespace: istio-system
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: wade.xu@demo.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: istio
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-tls-secret
  namespace: istio-system
spec:
  secretName: istio-tls-secret
  issuerRef:
    name: letsencrypt-prod-istio
    kind: Issuer
    group: cert-manager.io
  dnsNames:
  - istio-qw.wadexu.cloud
