# on boarding new cluster
# go to argo-kustomize folder, kustomize build argocd-manager | kubectl apply -f -
# Get token/ca.crt from kubectl edit secret argocd-manager-token -n kube-system
# then replace below config
apiVersion: v1
kind: Secret
metadata:
  name: gke-us-dev
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: gke-us-dev
  server: https://34.28.199.211
  config: |
    {
      "bearerToken": "<token>",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<ca.crt>"
      }
    }