apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- modules.yaml
- resolvers.yaml
patchesStrategicMerge:
- deployment-patch.yaml

# when you have both public and internal ambassador in one cluster
# need separate name of ClusterRoleBinding
patches:
- target:
    kind: ClusterRoleBinding
    name: ambassador
  patch: |-
    - op: replace
      path: /metadata/name
      value: ambassador-app

# replace container registry and ambassador version
images:
- name: docker.io/datawire/ambassador:\$version\$
  newName: docker.io/datawire/ambassador
  newTag: 1.12.1
