apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
- namespace.yaml
- secret.yaml

# patchesStrategicMerge is deprecated, use 'patches' instead
patches:
- path: deployment-patch.yaml
