---
## external sercret svc must install first
## sercret must uplaod to GCP Secret Manager first
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: kube-config
spec:
  backendType: gcpSecretsManager
  data:
    - key: kube-config
      name: kubeconfig
      isBinary: false

