apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- sa.yaml

namespace: atlantis

patchesStrategicMerge:
- statefulset.yaml

images:
- name: ghcr.io/runatlantis/atlantis
  newName: wadexu007/atlantis
  newTag: v0.18.2-3

