---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: atlantis

  # (Optional) for GKE Workload Identity: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
  # annotations:
  #   iam.gke.io/gcp-service-account: atlantis@global-sre-dev.iam.gserviceaccount.com
