apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/datawire/ambassador/v1.12.1/docs/yaml/ambassador/ambassador-crds.yaml
- https://raw.githubusercontent.com/datawire/ambassador/v1.12.1/docs/yaml/ambassador/ambassador-rbac.yaml
