---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  labels:
    app.kubernetes.io/component: ambassador-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 10.127.3.10
  selector:
    service: ambassador
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: 8080-to-8080
    port: 8080
    targetPort: http
