apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- sa.yaml

namespace: atlantis

patches:
  - path: statefulset-patch.yaml

  - target:
      kind: StatefulSet
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/1
        value: "--write-git-creds"
