apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atlantis
spec:
  template:
    spec:
      serviceAccountName: atlantis
      containers:
      - name: atlantis
        env:
        - name: ATLANTIS_ATLANTIS_URL
          value: https://atlantis-demo.wadexu.cloud
        - name: ATLANTIS_REPO_ALLOWLIST
          value: github.com/wadexu007/learning_by_doing
        # Github App integration
        - name: ATLANTIS_GH_APP_ID
          valueFrom:
            secretKeyRef:
              name: atlantis-github-app
              key: ghAppID
        - name: ATLANTIS_GH_APP_KEY
          valueFrom:
            secretKeyRef:
              name: atlantis-github-app
              key: ghAppKey
        - name: ATLANTIS_GH_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: atlantis-github-app
              key: ghWebhookSecret