apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    application-type: bootstrapper
  name: group-apps-gke-us-dev
spec:
  destination:
    namespace: argocd
    server: https://34.28.199.211
  project: default
  source:
    repoURL: https://github.com/wadexu007/learning_by_doing
    path: Argo/argo-apps/dev
    targetRevision: main
    directory:
      recurse: false
  syncPolicy:
    automated:
      selfHeal: true